package main

import "math/rand"

func ProfilOlustur(mevki string, yetenek int) Ozellikler {
	var player Ozellikler
	temelPuan := yetenek / 10

	if mevki == "Kaleci" {
		player.Degaj = temelPuan + rand.Intn(4) - 1
		player.KarsiKarsiya = temelPuan + rand.Intn(4) - 1
		player.Refleks = temelPuan + rand.Intn(4) - 1
		player.Ziplama = temelPuan + rand.Intn(4) - 1
		player.Bitiricilik = rand.Intn(8) + 1
		player.Caliskanlik = rand.Intn(8) + 1
		player.Cesaret = rand.Intn(8) + 1
		player.Ceviklik = rand.Intn(8) + 1
		player.Dayaniklilik = rand.Intn(8) + 1
		player.DefansifPozisyonAlma = rand.Intn(8) + 1
		player.Denge = rand.Intn(8) + 1
		player.Dribling = rand.Intn(8) + 1
		player.DuranToplar = rand.Intn(8) + 1
		player.Guc = rand.Intn(8) + 1
		player.Hiz = rand.Intn(8) + 1
		player.Hizlanma = rand.Intn(8) + 1
		player.IlkKontrol = rand.Intn(8) + 1
		player.KafaVurusu = rand.Intn(8) + 1
		player.KararAlma = rand.Intn(8) + 1
		player.Kararlilik = rand.Intn(8) + 1
		player.Konsantrasyon = rand.Intn(8) + 1
		player.Liderlik = rand.Intn(8) + 1
		player.Markaj = rand.Intn(8) + 1
		player.OnSezi = rand.Intn(8) + 1
		player.OrtaYapma = rand.Intn(8) + 1
		player.Pas = rand.Intn(8) + 1
		player.Sogukkanlilik = rand.Intn(8) + 1
		player.TaktigeBaglilik = rand.Intn(8) + 1
		player.Teknik = rand.Intn(8) + 1
		player.TopKapma = rand.Intn(8) + 1
		player.TopsuzAlan = rand.Intn(8) + 1
		player.UzaktanSut = rand.Intn(8) + 1
		player.Vizyon = rand.Intn(8) + 1
	} else if mevki == "Stoper" {
		player.TopKapma = temelPuan + rand.Intn(4) - 1
		player.Markaj = temelPuan + rand.Intn(4) - 1
		player.DefansifPozisyonAlma = temelPuan + rand.Intn(4) - 1
		player.Ziplama = temelPuan + rand.Intn(4) - 1
		player.Degaj = rand.Intn(8) + 1
		player.KarsiKarsiya = rand.Intn(8) + 1
		player.Refleks = rand.Intn(8) + 1
		player.Bitiricilik = rand.Intn(8) + 1
		player.Caliskanlik = rand.Intn(8) + 1
		player.Cesaret = rand.Intn(8) + 1
		player.Ceviklik = rand.Intn(8) + 1
		player.Dayaniklilik = rand.Intn(8) + 1
		player.Denge = rand.Intn(8) + 1
		player.Dribling = rand.Intn(8) + 1
		player.DuranToplar = rand.Intn(8) + 1
		player.Guc = rand.Intn(8) + 1
		player.Hiz = rand.Intn(8) + 1
		player.Hizlanma = rand.Intn(8) + 1
		player.IlkKontrol = rand.Intn(8) + 1
		player.KafaVurusu = rand.Intn(8) + 1
		player.KararAlma = rand.Intn(8) + 1
		player.Kararlilik = rand.Intn(8) + 1
		player.Konsantrasyon = rand.Intn(8) + 1
		player.Liderlik = rand.Intn(8) + 1
		player.OnSezi = rand.Intn(8) + 1
		player.OrtaYapma = rand.Intn(8) + 1
		player.Pas = rand.Intn(8) + 1
		player.Sogukkanlilik = rand.Intn(8) + 1
		player.TaktigeBaglilik = rand.Intn(8) + 1
		player.Teknik = rand.Intn(8) + 1
		player.TopsuzAlan = rand.Intn(8) + 1
		player.UzaktanSut = rand.Intn(8) + 1
		player.Vizyon = rand.Intn(8) + 1
	} else if mevki == "SolBek" || mevki == "SagBek" {
		player.TopKapma = temelPuan + rand.Intn(4) - 1
		player.Markaj = temelPuan + rand.Intn(4) - 1
		player.DefansifPozisyonAlma = temelPuan + rand.Intn(4) - 1
		player.Hiz = temelPuan + rand.Intn(4) - 1
		player.Hizlanma = temelPuan + rand.Intn(4) - 1
		player.OrtaYapma = temelPuan + rand.Intn(4) - 1
		player.Pas = temelPuan + rand.Intn(4) - 1
		player.Teknik = temelPuan + rand.Intn(4) - 1
		player.Dribling = temelPuan + rand.Intn(4) - 1
		player.Ziplama = rand.Intn(8) + 1
		player.Degaj = rand.Intn(8) + 1
		player.KarsiKarsiya = rand.Intn(8) + 1
		player.Refleks = rand.Intn(8) + 1
		player.Bitiricilik = rand.Intn(8) + 1
		player.Caliskanlik = rand.Intn(8) + 1
		player.Cesaret = rand.Intn(8) + 1
		player.Ceviklik = rand.Intn(8) + 1
		player.Dayaniklilik = rand.Intn(8) + 1
		player.Denge = rand.Intn(8) + 1
		player.DuranToplar = rand.Intn(8) + 1
		player.Guc = rand.Intn(8) + 1
		player.IlkKontrol = rand.Intn(8) + 1
		player.KafaVurusu = rand.Intn(8) + 1
		player.KararAlma = rand.Intn(8) + 1
		player.Kararlilik = rand.Intn(8) + 1
		player.Konsantrasyon = rand.Intn(8) + 1
		player.Liderlik = rand.Intn(8) + 1
		player.OnSezi = rand.Intn(8) + 1
		player.Sogukkanlilik = rand.Intn(8) + 1
		player.TaktigeBaglilik = rand.Intn(8) + 1
		player.TopsuzAlan = rand.Intn(8) + 1
		player.UzaktanSut = rand.Intn(8) + 1
		player.Vizyon = rand.Intn(8) + 1
	} else if mevki == "SolKanat" || mevki == "SagKanat" {
		player.Hiz = temelPuan + rand.Intn(4) - 1
		player.Hizlanma = temelPuan + rand.Intn(4) - 1
		player.OrtaYapma = temelPuan + rand.Intn(4) - 1
		player.Pas = temelPuan + rand.Intn(4) - 1
		player.Teknik = temelPuan + rand.Intn(4) - 1
		player.Dribling = temelPuan + rand.Intn(4) - 1
		player.UzaktanSut = temelPuan + rand.Intn(4) - 1
		player.Vizyon = temelPuan + rand.Intn(4) - 1
		player.Bitiricilik = temelPuan + rand.Intn(4) - 1
		player.Ziplama = rand.Intn(8) + 1
		player.TopKapma = rand.Intn(8) + 1
		player.Markaj = rand.Intn(8) + 1
		player.DefansifPozisyonAlma = rand.Intn(8) + 1
		player.Degaj = rand.Intn(8) + 1
		player.KarsiKarsiya = rand.Intn(8) + 1
		player.Refleks = rand.Intn(8) + 1
		player.Caliskanlik = rand.Intn(8) + 1
		player.Cesaret = rand.Intn(8) + 1
		player.Ceviklik = rand.Intn(8) + 1
		player.Dayaniklilik = rand.Intn(8) + 1
		player.Denge = rand.Intn(8) + 1
		player.DuranToplar = rand.Intn(8) + 1
		player.Guc = rand.Intn(8) + 1
		player.IlkKontrol = rand.Intn(8) + 1
		player.KafaVurusu = rand.Intn(8) + 1
		player.KararAlma = rand.Intn(8) + 1
		player.Kararlilik = rand.Intn(8) + 1
		player.Konsantrasyon = rand.Intn(8) + 1
		player.Liderlik = rand.Intn(8) + 1
		player.OnSezi = rand.Intn(8) + 1
		player.Sogukkanlilik = rand.Intn(8) + 1
		player.TaktigeBaglilik = rand.Intn(8) + 1
		player.TopsuzAlan = rand.Intn(8) + 1
	} else if mevki == "DefansifOrtaSaha" {
		player.OrtaYapma = temelPuan + rand.Intn(4) - 1
		player.Pas = temelPuan + rand.Intn(4) - 1
		player.Teknik = temelPuan + rand.Intn(4) - 1
		player.TopKapma = temelPuan + rand.Intn(4) - 1
		player.Markaj = temelPuan + rand.Intn(4) - 1
		player.DefansifPozisyonAlma = temelPuan + rand.Intn(4) - 1
		player.UzaktanSut = temelPuan + rand.Intn(4) - 1
		player.Vizyon = temelPuan + rand.Intn(4) - 1
		player.IlkKontrol = temelPuan + rand.Intn(4) - 1
		player.Bitiricilik = rand.Intn(8) + 1
		player.Dayaniklilik = rand.Intn(8) + 1
		player.Ziplama = rand.Intn(8) + 1
		player.Hiz = rand.Intn(8) + 1
		player.Dribling = rand.Intn(8) + 1
		player.Hizlanma = rand.Intn(8) + 1
		player.Degaj = rand.Intn(8) + 1
		player.KarsiKarsiya = rand.Intn(8) + 1
		player.Refleks = rand.Intn(8) + 1
		player.Caliskanlik = rand.Intn(8) + 1
		player.Cesaret = rand.Intn(8) + 1
		player.Ceviklik = rand.Intn(8) + 1
		player.Denge = rand.Intn(8) + 1
		player.DuranToplar = rand.Intn(8) + 1
		player.Guc = rand.Intn(8) + 1
		player.KafaVurusu = rand.Intn(8) + 1
		player.KararAlma = rand.Intn(8) + 1
		player.Kararlilik = rand.Intn(8) + 1
		player.Konsantrasyon = rand.Intn(8) + 1
		player.Liderlik = rand.Intn(8) + 1
		player.OnSezi = rand.Intn(8) + 1
		player.Sogukkanlilik = rand.Intn(8) + 1
		player.TaktigeBaglilik = rand.Intn(8) + 1
		player.TopsuzAlan = rand.Intn(8) + 1
	} else if mevki == "OrtaSaha" {
		player.OrtaYapma = temelPuan + rand.Intn(4) - 1
		player.Pas = temelPuan + rand.Intn(4) - 1
		player.Teknik = temelPuan + rand.Intn(4) - 1
		player.UzaktanSut = temelPuan + rand.Intn(4) - 1
		player.Vizyon = temelPuan + rand.Intn(4) - 1
		player.Dayaniklilik = temelPuan + rand.Intn(4) - 1
		player.IlkKontrol = temelPuan + rand.Intn(4) - 1
		player.Bitiricilik = rand.Intn(10) + 1
		player.Dribling = rand.Intn(12) + 1
		player.TopKapma = rand.Intn(12) + 1
		player.Markaj = rand.Intn(12) + 1
		player.DefansifPozisyonAlma = rand.Intn(12) + 1
		player.Ziplama = rand.Intn(8) + 1
		player.Hiz = rand.Intn(8) + 1
		player.Hizlanma = rand.Intn(8) + 1
		player.Degaj = rand.Intn(8) + 1
		player.KarsiKarsiya = rand.Intn(8) + 1
		player.Refleks = rand.Intn(8) + 1
		player.Caliskanlik = rand.Intn(8) + 1
		player.Cesaret = rand.Intn(8) + 1
		player.Ceviklik = rand.Intn(8) + 1
		player.Denge = rand.Intn(8) + 1
		player.DuranToplar = rand.Intn(8) + 1
		player.Guc = rand.Intn(8) + 1
		player.KafaVurusu = rand.Intn(8) + 1
		player.KararAlma = rand.Intn(8) + 1
		player.Kararlilik = rand.Intn(8) + 1
		player.Konsantrasyon = rand.Intn(8) + 1
		player.Liderlik = rand.Intn(8) + 1
		player.OnSezi = rand.Intn(8) + 1
		player.Sogukkanlilik = rand.Intn(8) + 1
		player.TaktigeBaglilik = rand.Intn(8) + 1
		player.TopsuzAlan = rand.Intn(8) + 1
	} else if mevki == "OfansifOrtaSaha" {
		player.OrtaYapma = temelPuan + rand.Intn(4) - 1
		player.Pas = temelPuan + rand.Intn(4) - 1
		player.Teknik = temelPuan + rand.Intn(4) - 1
		player.UzaktanSut = temelPuan + rand.Intn(4) - 1
		player.Vizyon = temelPuan + rand.Intn(4) - 1
		player.IlkKontrol = temelPuan + rand.Intn(4) - 1
		player.Bitiricilik = temelPuan + rand.Intn(4) - 1
		player.Dribling = temelPuan + rand.Intn(4) - 1
		player.Dayaniklilik = rand.Intn(12) + 1
		player.Ceviklik = rand.Intn(12) + 1
		player.Hiz = rand.Intn(12) + 1
		player.Hizlanma = rand.Intn(12) + 1
		player.TopKapma = rand.Intn(8) + 1
		player.Markaj = rand.Intn(8) + 1
		player.DefansifPozisyonAlma = rand.Intn(8) + 1
		player.Ziplama = rand.Intn(8) + 1
		player.Degaj = rand.Intn(8) + 1
		player.KarsiKarsiya = rand.Intn(8) + 1
		player.Refleks = rand.Intn(8) + 1
		player.Caliskanlik = rand.Intn(8) + 1
		player.Cesaret = rand.Intn(8) + 1
		player.Denge = rand.Intn(8) + 1
		player.DuranToplar = rand.Intn(8) + 1
		player.Guc = rand.Intn(8) + 1
		player.KafaVurusu = rand.Intn(8) + 1
		player.KararAlma = rand.Intn(8) + 1
		player.Kararlilik = rand.Intn(8) + 1
		player.Konsantrasyon = rand.Intn(8) + 1
		player.Liderlik = rand.Intn(8) + 1
		player.OnSezi = rand.Intn(8) + 1
		player.Sogukkanlilik = rand.Intn(8) + 1
		player.TaktigeBaglilik = rand.Intn(8) + 1
		player.TopsuzAlan = rand.Intn(8) + 1
	} else if mevki == "Forvet" {
		player.UzaktanSut = temelPuan + rand.Intn(4) - 1
		player.IlkKontrol = temelPuan + rand.Intn(4) - 1
		player.Bitiricilik = temelPuan + rand.Intn(4) - 1
		player.KafaVurusu = rand.Intn(8) + 1
		player.Dayaniklilik = rand.Intn(12) + 1
		player.Dribling = rand.Intn(12) + 1
		player.Ceviklik = rand.Intn(12) + 1
		player.OrtaYapma = rand.Intn(12) + 1
		player.Pas = rand.Intn(12) + 1
		player.Teknik = rand.Intn(12) + 1
		player.Vizyon = rand.Intn(12) + 1
		player.Hiz = rand.Intn(12) + 1
		player.OnSezi = rand.Intn(12) + 1
		player.Sogukkanlilik = rand.Intn(12) + 1
		player.Hizlanma = rand.Intn(12) + 1
		player.TopKapma = rand.Intn(8) + 1
		player.Markaj = rand.Intn(8) + 1
		player.DefansifPozisyonAlma = rand.Intn(8) + 1
		player.Ziplama = rand.Intn(8) + 1
		player.Degaj = rand.Intn(8) + 1
		player.KarsiKarsiya = rand.Intn(8) + 1
		player.Refleks = rand.Intn(8) + 1
		player.Caliskanlik = rand.Intn(8) + 1
		player.Cesaret = rand.Intn(8) + 1
		player.Denge = rand.Intn(8) + 1
		player.DuranToplar = rand.Intn(8) + 1
		player.Guc = rand.Intn(8) + 1
		player.KararAlma = rand.Intn(8) + 1
		player.Kararlilik = rand.Intn(8) + 1
		player.Konsantrasyon = rand.Intn(8) + 1
		player.Liderlik = rand.Intn(8) + 1
		player.TaktigeBaglilik = rand.Intn(8) + 1
		player.TopsuzAlan = rand.Intn(8) + 1
	}
	player.Bitiricilik = sinirla(player.Bitiricilik)
	player.UzaktanSut = sinirla(player.UzaktanSut)
	player.OnSezi = sinirla(player.OnSezi)
	player.Dribling = sinirla(player.Dribling)
	player.DuranToplar = sinirla(player.DuranToplar)
	player.Pas = sinirla(player.Pas)
	player.OrtaYapma = sinirla(player.OrtaYapma)
	player.Teknik = sinirla(player.Teknik)
	player.IlkKontrol = sinirla(player.IlkKontrol)
	player.Vizyon = sinirla(player.Vizyon)
	player.Markaj = sinirla(player.Markaj)
	player.TopKapma = sinirla(player.TopKapma)
	player.KafaVurusu = sinirla(player.KafaVurusu)
	player.DefansifPozisyonAlma = sinirla(player.DefansifPozisyonAlma)
	player.KararAlma = sinirla(player.KararAlma)
	player.TopsuzAlan = sinirla(player.TopsuzAlan)
	player.Caliskanlik = sinirla(player.Caliskanlik)
	player.Kararlilik = sinirla(player.Kararlilik)
	player.Cesaret = sinirla(player.Cesaret)
	player.Liderlik = sinirla(player.Liderlik)
	player.Sogukkanlilik = sinirla(player.Sogukkanlilik)
	player.Konsantrasyon = sinirla(player.Konsantrasyon)
	player.TaktigeBaglilik = sinirla(player.TaktigeBaglilik)
	player.Ceviklik = sinirla(player.Ceviklik)
	player.Dayaniklilik = sinirla(player.Dayaniklilik)
	player.Denge = sinirla(player.Denge)
	player.Guc = sinirla(player.Guc)
	player.Hiz = sinirla(player.Hiz)
	player.Hizlanma = sinirla(player.Hizlanma)
	player.Ziplama = sinirla(player.Ziplama)
	player.Refleks = sinirla(player.Refleks)
	player.Degaj = sinirla(player.Degaj)
	player.KarsiKarsiya = sinirla(player.KarsiKarsiya)

	return player
}
